#%RAML 1.0 ResourceType

get?:
  displayName: <<displayName>>
  description: Collection of <<resourcePathName | !singularize>>
  responses:
    504: &timeOut
      description: !include ../error-description/504-descriptions
      body:
        application/json:
          type: <<errorType>>
    503: &serviceUnavailable
      description: !include ../error-description/503-description
      body:
        application/json:
          type: <<errorType>>
    502: &badGateway
      description: !include ../error-description/502-description
      body:
        application/json:
          type: <<errorType>>
    500: &internalServerError
      description: !include ../error-description/500-description
      body:
        application/json:
          type: <<errorType>>
    429: &tooManyRequests
      description: !include ../error-description/429-description
      body:
        application/json:
          type: <<errorType>>
    422: &unprocessableEntity
      description: !include ../error-description/422-description
      body:
        application/json:
          type: <<errorType>>
    415: &unsupportedMediaType
      description: !include ../error-description/415-description
      body:
        application/json:
          type: <<errorType>>       
    407: &proxyAuthenticationRequired
      description: !include ../error-description/407-description
      body:
        application/json:
          type: <<errorType>>
    406: &notAcceptable
      description: !include ../error-description/406-description
      body:
        application/json:
          type: <<errorType>>
    405: &methodNotAllowed
      description: !include ../error-description/405-description
      body:
        application/json:
          type: <<errorType>>
    404: &notFound
      description: !include ../error-description/404-description
      body:
        application/json:
          type: <<errorType>>
    403: &forbidden
      description: !include ../error-description/403-description
      body:
        application/json:
          type: <<errorType>>       
    401: &notAuthorization
      description: !include ../error-description/401-description
      body:
        application/json:
          type: <<errorType>>
    400: &badRequest
      description: !include ../error-description/400-description
      body:
        application/json:
          type: <<errorType>>
    304:
      description: !include ../error-description/304-description
    200:
      description: Successfully retrieved a <<resourcePathName | !singularize>>. 
      body:
        application/json:
          type: <<collectionType>>[]
          example: <<collectionExample>>

post?:
  displayName: <<displayName>>
  description: Create a new <<resourcePathName | !singularize>>
  body:
    type: <<inputType>>
    example: <<inputExample>>
  responses:
    504: *timeOut
    503: *serviceUnavailable
    502: *badGateway
    500: *internalServerError
    429: *tooManyRequests
    422: *unprocessableEntity
    415: *unsupportedMediaType 
    407: *proxyAuthenticationRequired
    406: *notAcceptable 
    405: *methodNotAllowed
    404: *notFound
    403: *forbidden
    401: *notAuthorization
    400: *badRequest
    201:
      description: Created one/multiple new <<resourcePathName | !pluralize>>
      body:
        application/json:
          type: <<outputType>>
          example: <<outputExample>>
    202:
      description: Created one/multiple new <<resourcePathName | !pluralize>>
      body:
        application/json:
          type: <<outputType>>
          example: <<outputExample>>

put?:
  displayName: <<displayName>>
  description: Update <<resourcePathName | !singularize>>
  body:
    type: <<inputType>>
    example: <<inputExample>>
  responses:
    504: *timeOut
    503: *serviceUnavailable
    502: *badGateway
    500: *internalServerError
    429: *tooManyRequests
    422: *unprocessableEntity
    415: *unsupportedMediaType 
    407: *proxyAuthenticationRequired
    406: *notAcceptable 
    405: *methodNotAllowed
    404: *notFound
    403: *forbidden
    401: *notAuthorization
    400: *badRequest       
    204:
      description: Updated existing <<resourcePathName | !singularize>>

patch?:  
  displayName: <<displayName>>
  description: Partial Update <<resourcePathName | !singularize>>
  body:
    type: <<inputType>>
    example: <<inputExample>>
  responses:
    504: *timeOut
    503: *serviceUnavailable
    502: *badGateway
    500: *internalServerError
    429: *tooManyRequests
    422: *unprocessableEntity
    415: *unsupportedMediaType 
    407: *proxyAuthenticationRequired
    406: *notAcceptable 
    405: *methodNotAllowed
    404: *notFound
    403: *forbidden
    401: *notAuthorization
    400: *badRequest       
    204:
      description: Updated existing <<resourcePathName | !singularize>>    

delete?: 
  displayName: <<displayName>>
  description: Delete the {Id} from <<resourcePathName | !singularize>> 
  responses:
    504: *timeOut
    503: *serviceUnavailable
    502: *badGateway
    500: *internalServerError
    429: *tooManyRequests
    422: *unprocessableEntity
    415: *unsupportedMediaType 
    407: *proxyAuthenticationRequired
    406: *notAcceptable 
    405: *methodNotAllowed
    404: *notFound
    403: *forbidden
    401: *notAuthorization
    400: *badRequest       
    204:
      description: Deleted existing <<resourcePathName | !singularize>>             